#!/usr/bin/env python3
"""Refuse a commit whose directory maps no longer match the source files beside them."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path, PurePosixPath

CONFIG = ".agent-checks.toml"
TABLE = "codebase-map"

SOURCE_EXTENSIONS = frozenset(
    {
        ".c",
        ".cc",
        ".cpp",
        ".cs",
        ".dart",
        ".ex",
        ".exs",
        ".go",
        ".h",
        ".hpp",
        ".java",
        ".js",
        ".jsx",
        ".kt",
        ".lua",
        ".mjs",
        ".php",
        ".py",
        ".rb",
        ".rs",
        ".scala",
        ".sh",
        ".sql",
        ".svelte",
        ".swift",
        ".ts",
        ".tsx",
        ".vue",
        ".zig",
    }
)

EXCLUDED_NAMES = (
    "__init__.py",
    "conftest.py",
    "*_test.*",
    "test_*",
    "*.test.*",
    "*.spec.*",
)
EXCLUDED_DIRS = frozenset({"node_modules", "vendor"})

MAP_FILE = "AGENTS.md"
FALLBACK_MAP_FILE = "README.md"
GENERATED_MARKER = "generated by farrier"

HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
ENTRY = re.compile(r"^\s*[-*]\s+`([^`]+)`\s*(?:[:\u2014\u2013-]\s*)?(.*?)\s*$")

SKILL_HINT = "Load the codebase-map skill for how to write and keep the map."


@dataclass(frozen=True)
class Settings:
    extensions: frozenset[str]
    exclude: tuple[str, ...]


def _root() -> str:
    return subprocess.run(
        ("git", "rev-parse", "--show-toplevel"),
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


ROOT = _root()


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ("git", "-C", ROOT, *args), capture_output=True, text=True, check=check
    )


class ConfigError(ValueError):
    """A value in the config table has the wrong type."""


def config_strings(table: dict[str, object], key: str) -> tuple[str, ...]:
    value = table.get(key, [])
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ConfigError(f"{CONFIG} [{TABLE}] {key} must be a list of strings")
    return tuple(item for item in value if isinstance(item, str))


def load_settings() -> Settings:
    try:
        with Path(ROOT, CONFIG).open("rb") as handle:
            loaded = tomllib.load(handle).get(TABLE, {})
    except FileNotFoundError:
        loaded = {}
    if not isinstance(loaded, dict):
        raise ConfigError(f"{CONFIG} [{TABLE}] must be a table")
    table: dict[str, object] = {str(key): value for key, value in loaded.items()}
    extensions = config_strings(table, "extensions")
    return Settings(
        extensions=frozenset(extensions) if extensions else SOURCE_EXTENSIONS,
        exclude=config_strings(table, "exclude"),
    )


def is_source(path: str, settings: Settings) -> bool:
    pure = PurePosixPath(path)
    if pure.suffix not in settings.extensions:
        return False
    if any(part.startswith(".") or part in EXCLUDED_DIRS for part in pure.parts[:-1]):
        return False
    if any(fnmatch(pure.name, pattern) for pattern in EXCLUDED_NAMES):
        return False
    return not any(fnmatch(path, pattern) for pattern in settings.exclude)


def tracked_paths() -> list[str]:
    return [p for p in _git("ls-files", "-z").stdout.split("\0") if p]


def head_files() -> list[str]:
    result = _git("ls-tree", "-r", "-z", "--name-only", "HEAD", check=False)
    if result.returncode != 0:
        return []
    return [p for p in result.stdout.split("\0") if p]


def parent(path: str) -> str:
    value = str(PurePosixPath(path).parent)
    return "" if value == "." else value


def source_dirs(sources: list[str]) -> set[str]:
    """Every directory that holds a source file, directly or below."""
    holding_dirs: set[str] = set()
    for path in sources:
        directory = parent(path)
        while True:
            holding_dirs.add(directory)
            if directory == "":
                break
            directory = parent(directory)
    return holding_dirs


def names_the_map_must_list(directory: str, sources: list[str], source_holding_dirs: set[str]) -> set[str]:
    """The names a map for *directory* must list: source files and source subdirs."""
    names = {PurePosixPath(p).name for p in sources if parent(p) == directory}
    names |= {PurePosixPath(d).name + "/" for d in source_holding_dirs if d and parent(d) == directory}
    return names


def staged_text(path: str) -> str | None:
    result = _git("show", f":{path}", check=False)
    return result.stdout if result.returncode == 0 else None


def join(directory: str, name: str) -> str:
    return f"{directory}/{name}" if directory else name


def map_candidates(directory: str) -> list[str]:
    """Where a directory's map may live, in the order they are read."""
    agents = join(directory, MAP_FILE)
    text = staged_text(agents)
    if text is not None and GENERATED_MARKER in text[:600]:
        return [join(directory, FALLBACK_MAP_FILE)]
    return [agents, join(directory, FALLBACK_MAP_FILE)]


def map_path_and_section(directory: str) -> tuple[str, list[str] | None]:
    """The first candidate with a map section, or the preferred one when none has."""
    candidates = map_candidates(directory)
    for path in candidates:
        text = staged_text(path)
        section = map_section(text) if text is not None else None
        if section is not None:
            return path, section
    return candidates[0], None


def map_section(text: str) -> list[str] | None:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = HEADING.match(line)
        if match and match.group(2).lower() == "map":
            level = len(match.group(1))
            body: list[str] = []
            for rest in lines[index + 1 :]:
                deeper = HEADING.match(rest)
                if deeper and len(deeper.group(1)) <= level:
                    break
                body.append(rest)
            return body
    return None


def descriptions_by_listed_name(section: list[str]) -> dict[str, str]:
    descriptions: dict[str, str] = {}
    for line in section:
        match = ENTRY.match(line)
        if match:
            descriptions[match.group(1).strip()] = match.group(2)
    return descriptions


def map_problems(
    directory: str, sources: list[str], source_holding_dirs: set[str], tracked: set[str]
) -> list[str]:
    where = directory or "the repo root"
    path, section = map_path_and_section(directory)
    expected = names_the_map_must_list(directory, sources, source_holding_dirs)
    if section is None:
        lines = "\n".join(
            f"      - `{name}`: <what it owns>" for name in sorted(expected)
        )
        return [f"{where}: no `## Map` section in {path}. Add one:\n{lines}"]
    descriptions = descriptions_by_listed_name(section)
    problems: list[str] = []
    problems += [
        f"{path}: `{name}` is missing from the map. Add a line saying what it owns."
        for name in sorted(expected - descriptions.keys())
    ]
    for name in sorted(descriptions.keys() - expected):
        target = join(directory, name.rstrip("/"))
        exists = target in tracked or any(t.startswith(target + "/") for t in tracked)
        if not exists:
            problems.append(
                f"{path}: `{name}` is on the map but no longer exists. "
                "Remove or rename its line."
            )
    for name, description in sorted(descriptions.items()):
        if name in expected and not description:
            problems.append(f"{path}: `{name}` has no description. Say what it owns.")
    return problems


@dataclass(frozen=True)
class StagedChanges:
    """What the commit adds or deletes, and the directories whose map file it changes."""

    added_or_deleted_paths: tuple[str, ...]
    dirs_with_changed_map: tuple[str, ...]


def staged_changes() -> StagedChanges:
    name_status_output = _git("diff", "--cached", "--name-status", "--no-renames", "-z").stdout
    fields = [f for f in name_status_output.split("\0") if f]
    added_or_deleted: list[str] = []
    changed_map_dirs: list[str] = []
    for status, path in zip(fields[0::2], fields[1::2], strict=True):
        name = PurePosixPath(path).name
        if name in (MAP_FILE, FALLBACK_MAP_FILE):
            changed_map_dirs.append(parent(path))
        if status[0] in "AD":
            added_or_deleted.append(path)
    return StagedChanges(tuple(added_or_deleted), tuple(changed_map_dirs))


def dirs_to_check(
    settings: Settings,
    staged: StagedChanges,
    source_dirs_staged: set[str],
    source_dirs_at_head: set[str],
) -> set[str]:
    """Directories whose map this commit could have made wrong."""
    dirs_to_recheck = {d for d in staged.dirs_with_changed_map if d in source_dirs_staged}
    for path in staged.added_or_deleted_paths:
        if not is_source(path, settings):
            continue
        directory = parent(path)
        while True:
            if directory in source_dirs_staged or directory in source_dirs_at_head:
                dirs_to_recheck.add(directory)
            if directory == "" or (directory in source_dirs_staged) == (directory in source_dirs_at_head):
                break
            directory = parent(directory)
    return {d for d in dirs_to_recheck if d in source_dirs_staged}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--all",
        action="store_true",
        help="check every directory holding source, not only those the commit touches",
    )
    args = parser.parse_args(argv)
    try:
        settings = load_settings()
    except ConfigError as error:
        print(f"codebase-map: {error}", file=sys.stderr)
        return 1
    tracked = tracked_paths()
    sources = [p for p in tracked if is_source(p, settings)]
    source_holding_dirs = source_dirs(sources)
    if args.all:
        targets = source_holding_dirs
    else:
        head_sources = [p for p in head_files() if is_source(p, settings)]
        targets = dirs_to_check(settings, staged_changes(), source_holding_dirs, source_dirs(head_sources))
    problems: list[str] = []
    for directory in sorted(targets):
        problems += map_problems(directory, sources, source_holding_dirs, set(tracked))
    if not problems:
        return 0
    print("codebase-map: the map no longer matches the code.", file=sys.stderr)
    for problem in problems:
        print(f"  - {problem}", file=sys.stderr)
    print(f"  {SKILL_HINT}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
