#!/usr/bin/env python3
"""Refuse a commit whose directory maps no longer match the source files beside them."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path, PurePosixPath

CONFIG = ".agent-checks.toml"
TABLE = "codebase-map"

SOURCE_EXTENSIONS = frozenset(
    {
        ".c",
        ".cc",
        ".cpp",
        ".cs",
        ".dart",
        ".ex",
        ".exs",
        ".go",
        ".h",
        ".hpp",
        ".java",
        ".js",
        ".jsx",
        ".kt",
        ".lua",
        ".mjs",
        ".php",
        ".py",
        ".rb",
        ".rs",
        ".scala",
        ".sh",
        ".sql",
        ".svelte",
        ".swift",
        ".ts",
        ".tsx",
        ".vue",
        ".zig",
    }
)

EXCLUDED_NAMES = (
    "__init__.py",
    "conftest.py",
    "*_test.*",
    "test_*",
    "*.test.*",
    "*.spec.*",
)
EXCLUDED_DIRS = frozenset({"node_modules", "vendor"})

MAP_FILE = "AGENTS.md"
FALLBACK_MAP_FILE = "README.md"
GENERATED_MARKER = "generated by farrier"

HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
ENTRY = re.compile(r"^\s*[-*]\s+`([^`]+)`\s*(?:[:\u2014\u2013-]\s*)?(.*?)\s*$")

SKILL_HINT = "Load the codebase-map skill for how to write and keep the map."


@dataclass(frozen=True)
class Settings:
    extensions: frozenset[str]
    exclude: tuple[str, ...]


def _root() -> str:
    return subprocess.run(
        ("git", "rev-parse", "--show-toplevel"),
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


ROOT = _root()


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ("git", "-C", ROOT, *args), capture_output=True, text=True, check=check
    )


def settings() -> Settings:
    try:
        with Path(ROOT, CONFIG).open("rb") as handle:
            table = tomllib.load(handle).get(TABLE, {})
    except FileNotFoundError:
        table = {}
    extensions = table.get("extensions")
    return Settings(
        extensions=frozenset(extensions) if extensions else SOURCE_EXTENSIONS,
        exclude=tuple(table.get("exclude", ())),
    )


def is_source(path: str, config: Settings) -> bool:
    pure = PurePosixPath(path)
    if pure.suffix not in config.extensions:
        return False
    if any(part.startswith(".") or part in EXCLUDED_DIRS for part in pure.parts[:-1]):
        return False
    if any(fnmatch(pure.name, pattern) for pattern in EXCLUDED_NAMES):
        return False
    return not any(fnmatch(path, pattern) for pattern in config.exclude)


def index_files() -> list[str]:
    return [p for p in _git("ls-files", "-z").stdout.split("\0") if p]


def head_files() -> list[str]:
    result = _git("ls-tree", "-r", "-z", "--name-only", "HEAD", check=False)
    if result.returncode != 0:
        return []
    return [p for p in result.stdout.split("\0") if p]


def parent(path: str) -> str:
    value = str(PurePosixPath(path).parent)
    return "" if value == "." else value


def source_dirs(sources: list[str]) -> set[str]:
    """Every directory that holds a source file, directly or below."""
    out: set[str] = set()
    for path in sources:
        directory = parent(path)
        while True:
            out.add(directory)
            if directory == "":
                break
            directory = parent(directory)
    return out


def children(directory: str, sources: list[str], dirs: set[str]) -> set[str]:
    """The names a map for *directory* must list: source files and source subdirs."""
    names = {PurePosixPath(p).name for p in sources if parent(p) == directory}
    names |= {PurePosixPath(d).name + "/" for d in dirs if d and parent(d) == directory}
    return names


def staged_text(path: str) -> str | None:
    result = _git("show", f":{path}", check=False)
    return result.stdout if result.returncode == 0 else None


def join(directory: str, name: str) -> str:
    return f"{directory}/{name}" if directory else name


def map_candidates(directory: str) -> list[str]:
    """Where a directory's map may live, in the order they are read."""
    agents = join(directory, MAP_FILE)
    text = staged_text(agents)
    if text is not None and GENERATED_MARKER in text[:600]:
        return [join(directory, FALLBACK_MAP_FILE)]
    return [agents, join(directory, FALLBACK_MAP_FILE)]


def find_map(directory: str) -> tuple[str, list[str] | None]:
    """The first candidate with a map section, or the preferred one when none has."""
    candidates = map_candidates(directory)
    for path in candidates:
        text = staged_text(path)
        section = map_section(text) if text is not None else None
        if section is not None:
            return path, section
    return candidates[0], None


def map_section(text: str) -> list[str] | None:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = HEADING.match(line)
        if match and match.group(2).lower() == "map":
            level = len(match.group(1))
            body: list[str] = []
            for rest in lines[index + 1 :]:
                deeper = HEADING.match(rest)
                if deeper and len(deeper.group(1)) <= level:
                    break
                body.append(rest)
            return body
    return None


def entries(section: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in section:
        match = ENTRY.match(line)
        if match:
            out[match.group(1).strip()] = match.group(2)
    return out


def check_directory(
    directory: str, sources: list[str], dirs: set[str], tracked: set[str]
) -> list[str]:
    where = directory or "the repo root"
    path, section = find_map(directory)
    expected = children(directory, sources, dirs)
    if section is None:
        lines = "\n".join(
            f"      - `{name}`: <what it owns>" for name in sorted(expected)
        )
        return [f"{where}: no `## Map` section in {path}. Add one:\n{lines}"]
    listed = entries(section)
    problems: list[str] = []
    problems += [
        f"{path}: `{name}` is missing from the map. Add a line saying what it owns."
        for name in sorted(expected - listed.keys())
    ]
    for name in sorted(listed.keys() - expected):
        target = join(directory, name.rstrip("/"))
        exists = target in tracked or any(t.startswith(target + "/") for t in tracked)
        if not exists:
            problems.append(
                f"{path}: `{name}` is on the map but no longer exists. "
                "Remove or rename its line."
            )
    for name, description in sorted(listed.items()):
        if name in expected and not description:
            problems.append(f"{path}: `{name}` has no description. Say what it owns.")
    return problems


def staged_changes() -> tuple[list[str], list[str]]:
    out = _git("diff", "--cached", "--name-status", "--no-renames", "-z").stdout
    fields = [f for f in out.split("\0") if f]
    touched: list[str] = []
    maps: list[str] = []
    for status, path in zip(fields[0::2], fields[1::2], strict=True):
        name = PurePosixPath(path).name
        if name in (MAP_FILE, FALLBACK_MAP_FILE):
            maps.append(parent(path))
        if status[0] in "AD":
            touched.append(path)
    return touched, maps


def affected(config: Settings, dirs: set[str]) -> set[str]:
    """Directories whose map this commit could have made wrong."""
    touched, maps = staged_changes()
    before = source_dirs([p for p in head_files() if is_source(p, config)])
    out = {d for d in maps if d in dirs}
    for path in touched:
        if not is_source(path, config):
            continue
        directory = parent(path)
        while True:
            if directory in dirs or directory in before:
                out.add(directory)
            if directory == "" or (directory in dirs) == (directory in before):
                break
            directory = parent(directory)
    return {d for d in out if d in dirs}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--all",
        action="store_true",
        help="check every directory holding source, not only those the commit touches",
    )
    args = parser.parse_args(argv)
    config = settings()
    tracked = index_files()
    sources = [p for p in tracked if is_source(p, config)]
    dirs = source_dirs(sources)
    targets = dirs if args.all else affected(config, dirs)
    problems: list[str] = []
    for directory in sorted(targets):
        problems += check_directory(directory, sources, dirs, set(tracked))
    if not problems:
        return 0
    print("codebase-map: the map no longer matches the code.", file=sys.stderr)
    for problem in problems:
        print(f"  - {problem}", file=sys.stderr)
    print(f"  {SKILL_HINT}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
